POST http://localhost:3000/api/blogs
content-type: application/json

{
		"title": "Another Title",
		"author": "Edsger W. Dijkstra",
		"url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
	}