DELETE http://localhost:3000/api/blogs/61704b20d8ea713f72a36f8f
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbWVvbmVlbHNlIiwiaWQiOiI2MTcwNDI2NmE0ZWU3NjM2NWE4OGJhYmUiLCJpYXQiOjE2MzQ4MDgxNDR9.ZVSJWP97c-StLf36U4f32wKJqdwNpne-9ctDzEn5tnY